const getWikisourcesLang = function(){
    return {
        "ang": "Ænglisc",
        "ar": "العربية",
        "as": "অসমীয়া",
        "az": "Azərbaycanca",
        "ban": "Bali",
        "be": "Беларуская",
        "bg": "Български",
        "bn": "বাংলা",
        "br": "Brezhoneg",
        "bs": "Bosanski",
        "ca": "Català",
        "cs": "Čeština",
        "cy": "Cymraeg",
        "da": "Dansk",
        "de": "Deutsch",
        "el": "Ελληνικά",
        "en": "English",
        "eo": "Esperanto",
        "es": "Español",
        "et": "Eesti",
        "eu": "Euskara",
        "fa": "فارسی",
        "fi": "Suomi",
        "fo": "Føroyskt",
        "fr": "Français",
        "gl": "Galego",
        "gu": "ગુજરાતી",
        "he": "עברית",
        "hi": "हिन्दी",
        "hr": "Hrvatski",
        "ht": "Krèyol ayisyen",
        "hu": "Magyar",
        "hy": "Հայերեն",
        "id": "Bahasa Indonesia",
        "is": "Íslenska",
        "it": "Italiano",
        "ja": "日本語",
        "jv": "Basa Jawa",
        "kn": "ಕನ್ನಡ",
        "ko": "한국어",
        "la": "Latina",
        "li": "Limburgs",
        "lij": "Lìgure",
        "lt": "Lietuvių",
        "mk": "Македонски",
        "ml": "മലയാളം",
        "mr": "मराठी",
        "nap": "Nnapulitano",
        "nl": "Nederlands",
        "no": "Norsk (Bokmål)",
        "or": "ଓଡ଼ିଆ",
        "pa": "ਪੰਜਾਬੀ",
        "pl": "ਪੰਜਾਬੀ",
        "pms": "Piemontèis",
        "pt": "Português",
        "ro": "Română",
        "ru": "Русский",
        "sa": "संस्कृतम्",
        "sah": "Саха тыла (Saxa Tyla)",
        "sk": "Slovenčina",
        "sl": "Slovenščina",
        "sr": "Српски / Srpski",
        "sv": "Svenska",
        "ta": "தமிழ்",
        "te": "తెలుగు",
        "th": "ไทย",
        "tr": "Türkçe",
        "uk": "Українська",
        "vec": "Vèneto",
        "vi": "Tiếng Việt",
        "wa": "Walon",
        "yi": "ייִדיש",
        "zh": "中文",
        "zh-min-nan": "Bân-lâm-gú"
    }
}

export { getWikisourcesLang }